### ISSUE TITLE
Deprecation messages

### ISSUE THREAD

**Issue by geekyme** [css-modules/css-modules-require-hook#36]
getting these messages when I load up app

```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#before is deprecated. Use Node#raws.before
Node#removeSelf is deprecated. Use Node#remove.
```

**Comment by sullenor** [comment]
Yeah, thank you for the info. It is a problem with the postcss plugins, used by require hook. Plugins expect postcss version 4 and should be updated in order to be used with version 5.

I'll link this ticket to the actual one to keep you informed. https://github.com/css-modules/css-modules-loader-core/issues/21

**Comment by sullenor** [comment]
I think that it was solved now. Checkout the second version.
