### ISSUE TITLE
How to customize resolve rules in order to align with webpack configuration

### ISSUE THREAD

**Issue by nightire** [css-modules/css-modules-require-hook#71]
On client side, webpack can use `resolve.alias` to helps you shorten module resolving rules. If I specify:

```javascript
resolve: {
  alias: { common: path.resolve('some/path/to/common') }
}
```

I can write something like:

```css
.example {
  composes: one-helper from 'common/helpers';
}
```

and webpack will resolve `'common/helpers'` to `'./some/path/to/common'`, and it works very well on client side.

How to achieve this functionality on server-side by using css-module-require-hook? I've solved many types of modules, only except for css modules. Thanks in advance.

**Comment by sullenor** [comment]
Hello,

Since I use [require.extensions](https://nodejs.org/api/globals.html#globals_require_extensions) to resolve `require` calls in runtime there are not many possibilities here and they may affect all the `require` calls in runtime. 

Anyways, you may use global [NODE_PATH](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) environment variable (see the reference for the proper usage) and provide particular paths where node.js will search for the modules. I used it in early versions to test loading from the `node_modules` folder: 

https://github.com/css-modules/css-modules-require-hook/blob/3.0.0/package.json#L16
https://github.com/css-modules/css-modules-require-hook/tree/3.0.0/test/tokens

**Comment by nightire** [comment]
Great, I'll look into that, thanks for your advices.
