### ISSUE TITLE
Cannot resolve module 'postcss-less'

### ISSUE THREAD

**Issue by peter-mouland** [css-modules/css-modules-require-hook#79]
Hi,  I've started to get the following error in the build stage of my app.

```sh
ERROR in ./~/css-modules-require-hook/test/api/processorOpts.js
Module not found: Error: Cannot resolve module 'postcss-less' in /Users/peterm/Workspace/personal/react-lego/node_modules/css-modules-require-hook/test/api
 @ ./~/css-modules-require-hook/test/api/processorOpts.js 5:19-42
```

my config file is (no mention of less): 

```js
const sass = require('node-sass');
module.exports = {
  generateScopedName: '[path]___[name]__[local]___[hash:base64:5]',
  extensions: ['.scss'],
  preprocessCss: (data, filename) =>
    sass.renderSync({
      data,
      file: filename,
    }).css,
};
```

I see your package.json has a devDependency `"postcss-less": "^0.2.0",` which looks correct to me as you are using this module for tests.

I suspect the tests are being run accidentally. Is that a post install script that runs the tests which is inadvertently being run when people `npm i` this module?

> this is the code changes i have done to get css-modules to work : https://github.com/peter-mouland/react-lego/commit/63b535c61ba61e964b16cba0a5b6ce64bffc3ebb

**Comment by sullenor** [comment]
I don't have any `postinstall` scripts in the `package.json` file as you may find. Only `prepublish` script which compiles the server code. But it's guarded with [in-publish](https://github.com/iarna/in-publish) module, so it wont be executed after `npm i`. So I doubt that tests were being run accidentally.

I checked the related issue and looks like that problem comes from the webpack. In the begining you may find that it tries to compile hooks modules: 

```
WARNING in ./~/css-modules-require-hook/preset.js
Critical dependencies:
13:7-22 the request of a dependency is an expression
 @ ./~/css-modules-require-hook/preset.js 13:7-22
```

Anyways looks like I forgot to add test folder to the `.npmignore` so it wont be available after publication, but still you have to find the way to exclude require hook from the compile step in the webpack config.

**Comment by sullenor** [comment]
I published version 4.0.4 so you wont get any problem with tests for now, but still you have to exclude require hook from the compiled files.

**Comment by peter-mouland** [comment]
Thanks.  I'll look into the exclusion

**Comment by peter-mouland** [comment]
I've stopped using the `preset` option in favour of the manual config option.  This is because the plugin/hook is also needed for server-side rendering (and my server files are compiled).
